---
title: "R101: A practical guide to using R"
output: 
  html_document:
    allign: right
    theme: flatly
    highlight: monochrome
    css: ~/Desktop/Git/Webpage/datamustflow/public/css/coder.min.a4f332213a21ce8eb521670c614470c58923aaaf385e2a73982c31dd7642decb.css
    toc: true
    toc_depth: 5
    toc_float: true
---

# Course characteristic

This course has three main goals. The first is to eliminate dependence on paid statistical software, which may be unavailable for financial reasons and which provides the user with relatively limited work options.

Secondly, this course aims to promote interest in R as the programming language with (almost) endless analytical possibilities and vibrant global community.

Last but not least, I would like you to have fun. Learning something like doing data analysis in R may not be easy. However, it could be quite enjoyable too. I admire [Andy Field](https://www.discoveringstatistics.com/) for his humorous, yet comprehensive way of teaching complex abstract topics such as factor rotation. My humble aspiration is to make learning R joyful, even if for a bit.

So, what exactly can you expect?

# Covered topics
##### 01. PROGRAMMING LANGUAGE R

a) Conceptual introduction to R
b) Installing R and RStudio, an introduction to the environment, packages
c) Fundamentals – using R as a calculator, assigning values to objects, objects classes
d) Coding etiquette

<u>Additional materials</u>:

* Muenchen, R. A. (2011). R for SAS and SPSS Users. Springer: New York.
* Norman, M. (2011). The Art of R Programming. No Starch Press: San Francisco.
* Coding etiquette – https://ourcodingclub.github.io/2017/04/25/etiquette.html
* Getting started with R and RStudio – https://ourcodingclub.github.io/2016/11/13/intro-to-r.html
* Google’s R Style Guide – https://google.github.io/styleguide/Rguide.xml
* R basics, workspace and working directory, RStudio projects – http://stat545.com/block002_hello-rworkspace-wd-project.html
* RStudio IDE Cheat Sheet – https://www.rstudio.com/wp-content/uploads/2016/01/rstudio-IDE-cheatsheet.pdf
* Base R Cheat Sheet – https://www.rstudio.com/wp-content/uploads/2016/05/base-r.pdf

##### 02. DATA OBJECTS AND CLASSES

a) Vector
b) Matrix
c) Factors
d) Data Frames
e) Lists

<u>Additional materials</u>:

* Muenchen, R. A. (2011). R for SAS and SPSS Users. Springer: New York.
* Navarro, D. J. (2014). Learning statistics with R: A tutorial for psychology students and other beginners. Available online: http://www.fon.hum.uva.nl/paul/lot2015/Navarro2014.pdf
* Norman, M. (2011). The Art of R Programming. No Starch Press: San Francisco.

##### 03. IMPORTING DATA
a) .csv
b) .txt
c) .xlsx
d) .sav

<u>Additional materials</u>:

* Muenchen, R. A. (2011). R for SAS and SPSS Users. Springer: New York.
* Navarro, D. J. (2014). Learning statistics with R: A tutorial for psychology students and other beginners. Available online: http://www.fon.hum.uva.nl/paul/lot2015/Navarro2014.pdf
* Data Import : : CHEAT SHEET – https://ugoproto.github.io/ugo_r_doc/data-import.pdf

##### 04. CLEANING DATA 
a) Messy data, tidy data
b) Date and time, strings
c) Missing values, outliers, errors

<u>Additional materials</u>:

* Muenchen, R. A. (2011). R for SAS and SPSS Users. Springer: New York.
* Navarro, D. J. (2014). Learning statistics with R: A tutorial for psychology students and other beginners. Available online: http://www.fon.hum.uva.nl/paul/lot2015/Navarro2014.pdf
* Norman, M. (2011). The Art of R Programming. No Starch Press: San Francisco.

##### 05. WRANGLING DATA (TIDYVERSE)
a) tbl
b) select, mutate
c) filter, arrange
d) summarise, %>%
e) group_by

<u>Additional materials</u>:

* Data Wrangling with dplyr and tidyr Cheat Sheet – https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf

##### 06. EXPLORATING DATA 
a) Categorical data
b) Continuous data

<u>Additional materials</u>:

* Muenchen, R. A. (2011). R for SAS and SPSS Users. Springer: New York.
* Navarro, D. J. (2014). Learning statistics with R: A tutorial for psychology students and other beginners. Available online: http://www.fon.hum.uva.nl/paul/lot2015/Navarro2014.pdf
* Norman, M. (2011). The Art of R Programming. No Starch Press: San Francisco.

##### 07. VISUALISATIONS
a) Bar chart
b) Histogram
c) Boxplot
d) Error bar
e) Scatterplot
f) Pirate plot

<u>Additional materials</u>:

* Kabacoff, R. I. (2011). R in Action Data analysis and graphics with R. Manning: Shelter Island.
* Wickham, H. (2009). ggplot2: Elegant Graphics for Data Analysis. Available online: http://moderngraphics11.pbworks.com/f/ggplot2-Book09hWickham.pdf.
* Data Visualization with ggplot2 Cheat Sheet – https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf

##### 08. GROUP COMPARISONS
a) t-test (one-sample, two independent and two dependent samples), Student's and Welch's t-test
b) ANalysis Of VAriance (ANOVA)

<u>Additional materials</u>:

* Field, A., Miles, J., & Field, Z. (2012). Discovering Statistics Using R. Sage: UK.
* Lakens, D. (n.d.). The perfect t-test. Staženo dne 8. 10. 2016. Dostupné online na: http://daniellakens.blogspot.cz/2015/05/the-perfect-t-test.html
* Navarro, D. J. (2014). Learning statistics with R: A tutorial for psychology students and other beginners. Available online: http://www.fon.hum.uva.nl/paul/lot2015/Navarro2014.pdf
* Verzani, J. (2014). Using R for Introductory Statistics (2. edice). Chapman & Hall: Boca Raton.

##### 09. CORRELATION, LINEAR REGRESSION
a) Correlation (Pearson's r, Spearman's rho, Kendall's tau)
b) Linear regression

<u>Additional materials</u>:

* Field, A., Miles, J., & Field, Z. (2012). Discovering Statistics Using R. Sage: UK.
* Navarro, D. J. (2014). Learning statistics with R: A tutorial for psychology students and other beginners. Available online: http://www.fon.hum.uva.nl/paul/lot2015/Navarro2014.pdf

##### 10. MULTIPLE LINEAR AND LOGISTIC REGRESSIONS
a) Multiple linear regression
b) Logistic regression

<u>Additional materials</u>:

* Field, A., Miles, J., & Field, Z. (2012). Discovering Statistics Using R. Sage: UK.
* Navarro, D. J. (2014). Learning statistics with R: A tutorial for psychology students and other beginners. Available online: http://www.fon.hum.uva.nl/paul/lot2015/Navarro2014.pdf
* Verzani, J. (2014). Using R for Introductory Statistics (2. edice). Chapman & Hall: Boca Raton

##### 11. MULTILEVEL AND MIXED MODELS
a) Introduction to multilevel and mixed models
b) Linear mixed-effect models
c) Generalized linear mixed-effect models
d) Repeated Measures

<u>Additional materials</u>:

* Field, A., Miles, J., & Field, Z. (2012). Discovering Statistics Using R. Sage: UK.

<hr />
&nbsp;
&nbsp;
<p style="text-align: center;"><b>Go back to <a href="/projects/projects.html">Projects</b></a></p>